name: Publish Docker

on:
  push:
    branches: [ master ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          registry: docker.pkg.github.com
          name: morder.net/api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "morder.net"
          workdir: ../src/api/

  build-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          registry: docker.pkg.github.com
          name: morder.net/bot
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "morder.bot"
          workdir: ../src/bot/
